# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20161208_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
