 version: '2'
 services:
   db:
     image: postgres
     container_name: simplemooc-db
     
   web:
     image: willsilvano/python
     container_name: simplemooc-web
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db