# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161129_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'O nome do usuário só pode conter letras, dígitos e caracteres @/./+/-/_', 'invalid')], verbose_name='Nome de usuário'),
        ),
    ]
